apiVersion: v2
appVersion: 1.30-alpha.2960dede6e8c225a6b0eef65199ade0367fba316
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

